mapping:
  Tristan Lins <tristan@lins.io>:
    - Tristan Lins <tristan.lins@bit3.de>
    - Tristan Lins <tristan.lins@infinitysoft.de>

  Christopher Bölter <christopher@boelter.eu>:
    - cboelter <christopher@boelter.eu>

