services:
  cca.meta_palettes.listeners.meta_models_builders:
    class: ContaoCommunityAlliance\MetaPalettes\Listener\MetaPalettesBuilder
    tags:
      - { name: 'kernel.event_listener', event: 'dc-general.factory.build-data-definition', method: 'process', priority: 200 }

  cca.meta_palettes.listener.build_palettes_listener:
    class: ContaoCommunityAlliance\MetaPalettes\Listener\BuildPalettesListener
    arguments:
      - '@cca.meta_palettes.parser'
      - '@cca.meta_palettes.interpreter.string_palettes'

  cca.meta_palettes.listener.sub_select_palettes_listener:
    class: ContaoCommunityAlliance\MetaPalettes\Listener\SubSelectPalettesListener
